package com.teammovil.domain.rules

object RulesErrors {

    const val NAME_FIELD_EMPTY_ERROR = 20001
    const val DESCRIPTION_FIELD_EMPTY_ERROR = 20010
    const val RACE_FIELD_EMPTY_ERROR = 20020
    const val GENDER_FIELD_EMPTY_ERROR = 20030
    const val TYPE_FIELD_EMPTY_ERROR = 20040
    const val BIRTH_DATE_FIELD_EMPTY_ERROR = 20050
    const val RESCUE_DATE_FIELD_EMPTY_ERROR = 20060
    const val MAIN_PHOTO_FIELD_EMPTY_ERROR = 20070

    const val ACTIVITY_START_DATE_FIELD_EMPTY_ERROR = 20080
    const val EMAIL_FIELD_EMPTY_ERROR = 20090
    const val PASSWORD_FIELD_EMPTY_ERROR = 20100
    const val PHONE_FIELD_EMPTY_ERROR = 20110
    const val ADDRESS_FIELD_EMPTY_ERROR = 20120

    const val FIRST_LAST_NAME_FIELD_EMPTY_ERROR = 20130
    const val SECOND_LAST_NAME_FIELD_EMPTY_ERROR = 20140
    const val MAIL_FIELD_EMPTY_ERROR = 20150

    const val EVIDENCE_PHOTO_FIELD_EMPTY_ERROR = 20200
    const val EVIDENCE_DATE_FIELD_EMPTY_ERROR = 20210
    const val EVIDENCE_COMMENTS_FIELD_EMPTY_ERROR = 20220

}